# Config file for automatic testing at travis-ci.org

# Only test maint, master and pull requests; skip tags.
# Other branches can allow themselves.
branches:
  only:
    - maint
    - master
    - next

# Prefer docker containers
sudo: required

language: python

python:
  - "2.7"

cache: pip

matrix:
  include:
  - python: "2.7"
    env: TOXENV=py27
  - python: "3.4"
    env: TOXENV=py34
  - python: "3.5"
    env: TOXENV=py35
  - python: "3.6"
    env: TOXENV=py36
  - python: "3.7"
    dist: xenial
    env: TOXENV=py37
  - python: "2.7"
    env: TOXENV=py27-flake8
  - python: "3.7"
    dist: xenial
    env: TOXENV=py37-flake8
  - python: "pypy2.7-6.0"
    env: TOXENV=pypy

  fast_finish: true

install:
  - travis_retry pip install --upgrade "pip < 19.1" setuptools tox ppu

script:
  - tox

before_cache:
  - remove-old-files.py -o 180 ~/.cache/pip
